Algoritmo "exercicioParesConsecutivos"


Var

   X, soma : inteiro

Inicio

   Escreva ( "Digite un numero inteiro: ")
   leia (X)
   
   soma <- 2
   
   enquanto x <> 0 faca
      
      Se X % 2 <> 0 entao
         X<- X + 1
      fimse
      
   soma <- 5 * X + 20
   
    escreval ( "Soma : ", soma)
    
    escreva ( "Digita um numero inteiro: ")
    leia (X)
    
   fimenquanto
   


Fimalgoritmo