Algoritmo "exerciciomenordetres"

Var
   a, b, c : real
   

Inicio

   escreva ( "primeiro valor: ")
   leia (a)
   escreva ( "segundo valor: ")
   leia (b)
   escreva ( "terceiro valor: ")
   leia (c)

   Se a < b entao
      escreva ( "Menor = ", a)
   senão
        se b < c entao
           escreva (  "Menor = ", b)
        senão
           escreva (  "Menor = ", c)
        Fimse
   fimse
Fimalgoritmo